quarkus:
  application:
    name: demo-app
  profile:
    dev
  devservices:
    enabled: false
  native:
    resources:
      includes: publicKey.pem
  # http
  # https://quarkus.io/guides/http-reference
  http:
    port: 8080
    auth:
      proactive: true #
      permission:
        authenticated:
          paths: /*
          policy: authenticated
        public:
          paths: /auth/*
          policy: permit
    #access-log:
    #  pattern:
  config-tracking:
    enabled: true
  # OAS
  swagger-ui:
    always-include: true
    theme: material
  smallrye-openapi:
    management:
      enabled: false
  # logging
  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
    file:
      enable: true
      path: logs/application.log
      async: true
      async.queue-length: 100
      async.overflow: discard
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
      rotation:
        max-file-size: 10M
        max-backup-index: 5
    category:
      io.quarkus.vertx.http.access:
        level: DEBUG
      org.hibernate:
        level: DEBUG
  # datasource
  datasource:
    devservices:
      enabled: false
    health:
      enabled: true
    metrics:
      enabled: true
    #
    db-kind: postgresql
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:pgdev01}
    # default
    jdbc:
      enable-metrics: true
      initial-size: 5
      telemetry: true
      min-size: 5
      max-size: 10
      validate-on-borrow: true
      pooling-enabled: true
      url: jdbc:postgresql://${PG_HOST:localhost:15432}/${PG_DB:postgres}?currentSchema=${PG_SCHEMA:demo-service}&autoReconnect=true&serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true&stringtype=unspecified
      validation-query-sql: SELECT NOW()
  # orm
  hibernate-orm:
    statistics: true
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    metrics:
      enabled: true
    validation:
      enabled: true
    database:
      generation: none
    flush:
      mode: auto
    log:
      sql: true
      queries-slower-than-ms: 1000
  # redis
  redis:
    hosts: ${REDIS_HOST:redis://localhost:6379/0}
    max-pool-size: 5
    timeout: 5s
    orders:
      timeout: 10s
  # cache
  cache:
    type: redis
    redis:
      expire-after-write: 300s
      orders-cache:
        prefix: orders
        value-type: com.example.demo.model.Order
      posts-cache:
        prefix: posts
        value-type: com.example.demo.integration.model.FakePost
  # REST Client
  rest-client:
    logging:
      scope: request-response
      body-limit: 50
    fake-post-client:
      url: https://jsonplaceholder.typicode.com
      scope: jakarta.inject.Singleton
  # OTEL
  otel:
    resource:
      attributes: deployment.environment=dev,service.name=demo-orders,service.namespace=demo
    metrics:
      enabled: true
      exporter: logging # otlp
    traces:
      enabled: true
      eusp:
        enabled: true
      sampler: traceidratio
      sampler.arg: 1.0
      exporter: logging # otlp
    metric:
      export:
        interval: 1000ms
    # for dev/sit/uat/prod
    #exporter:
    #  otlp:
    #    endpoint: http://localhost:4317
  # metrics
  management:
    enabled: true
  micrometer:
    export:
      json:
        enabled: true
        path: metrics/json
      prometheus:
        path: metrics/prometheus
  # oidc
  # $auth-server/.well-known/openid-configuration
  oidc:
    auth-server-url: http://localhost:3080/realms/quarkus
#    discovery-enabled: false
#    authorization-pth: /protocol/openid-connect/auth
#    token-path: /protocol/openid-connect/token
#    jwks-path: /protocol/openid-connect/certs
#    user-info-path: /protocol/openid-connect/userinfo
#    introspection-path: /protocol/openid-connect/token/introspect
#    end-session-path: /protocol/openid-connect/logout
    client-id: frontend
    credentials:
      secret: secret
    application-type: hybrid # web-app, service, hybrid
    authentication:
      #redirect-path: /auth/callback
      #restore-path-after-redirect: true
      cookie-path: /
      error-path: /auth/error
      pkce-required: true
      allow-multiple-code-flows: false # disable multi-tab authentication
      # state-secret: eUk1p7UB3nFiXZGUXi0uph1Y9p34YhBU # will be auto generated
      # session-age-extension: 600s
    token-state-manager:
      split-tokens: true
      strategy: keep-all-tokens # default is keep-all-tokens
      encryption-required: true
      encryption-secret: eUk1p7UB3nFiXZGUXi0uph1Y9p34YhBU # 32 characters long
    logout:
      path: /logout
      post-logout-path: /tokens
    token:
      refresh-expired: true
# kafka
kafka:
  group:
    id: demoService-orders
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:39192}
smallrye:
  messaging:
    observation:
      enabled: true
# messaging
mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
        algorithm: RS256
      issuer: https://example.com/issuer
      audiences: demo-app
      age: 600
  messaging:
    connector:
      smallrye-kafka:
        client-id-prefix: orders
        # producer
        retries: 3
        acks: 1
        max-inflight-messages: 10
        # consumer
        enable.auto.commit: false
        auto.offset.reset: latest
        retry-max-wait: 10
        #failure-strategy: dead-letter-queue
        max.poll.records: 1000
        isolation.level: read_committed
    incoming:
      ordersIn:
        connector: smallrye-kafka
        topic: demoService-orders
        #dead-letter-queue:
        #  topic: demoService-orders-dlq
        value:
          deserializer: com.example.demo.messaging.serde.OrderMessageDeserializer
    outgoing:
      ordersOut:
        connector: smallrye-kafka
        transactional.id: demoService-orders-${quarkus:uuid}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer