quarkus:
  devservices:
    enabled: false
  native:
    resources:
      includes: publicKey.pem
  # OAS
  swagger-ui:
    always-include: true
  # logging
  log:
    level: INFO
    category:
      io.quarkus.vertx.http.access:
        level: DEBUG
      org.hibernate:
        level: DEBUG
  # datasource
  datasource:
    devservices:
      enabled: false
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:15432/postgres?currentSchema=demo-service&autoReconnect=true&serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true&stringtype=unspecified
    username: postgres
    password: pgdev01
  # orm
  hibernate-orm:
    statistics: true
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    metrics:
      enabled: true
    validation:
      enabled: true
    database:
      generation: none
    flush:
      mode: auto
  # redis
  redis:
    hosts: redis://localhost:6379/0
    timeout: 5s
  # cache
  cache:
    type: redis
    redis:
      expire-after-write: 300s
      orders-cache:
        prefix: orders
        value-type: com.example.demo.model.Order
      posts-cache:
        prefix: posts
        value-type: com.example.demo.integration.model.FakePost
  # REST Client
  rest-client:
    logging:
      scope: request-response
      body-limit: 50
    fake-post-client:
      url: https://jsonplaceholder.typicode.com
      scope: jakarta.inject.Singleton

# kafka
kafka:
  group:
    id: demoService-orders
  bootstrap:
    servers: localhost:39192
# messaging
mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
        algorithm: RS256
      issuer: https://example.com/issuer
      audiences: demo-app
      age: 600
  messaging:
    connector:
      smallrye-kafka:
        client-id-prefix: orders
        # producer
        retries: 3
        acks: 1
        max-inflight-messages: 10
        # consumer
        enable.auto.commit: false
        auto.offset.reset: latest
        retry-max-wait: 10
        #failure-strategy: dead-letter-queue
        max.poll.records: 1000
        isolation.level: read_committed
    incoming:
      ordersIn:
        connector: smallrye-kafka
        topic: demoService-orders
        #dead-letter-queue:
        #  topic: demoService-orders-dlq
        value:
          deserializer: com.example.demo.messaging.serde.OrderMessageDeserializer
    outgoing:
      ordersOut:
        connector: smallrye-kafka
        transactional.id: demoService-orders-${quarkus:uuid}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer